"use client";

import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { CampaignPerformance, CreativePerformance } from "@/lib/analytics/acquisition-report";
import type { Ga4AcquisitionReport, Ga4SeriesRow } from "@/lib/analytics/ga4-data";
import { channelName, isPublicLanding } from "@/lib/analytics/acquisition";

type Summary = { arrivals: number; signupStarts: number; signups: number; tiktokSignups: number; premium: number; checkouts: number; campaigns: CampaignPerformance[]; creatives: CreativePerformance[] };
const format = (value: number) => value.toLocaleString("pt-BR");
const ratio = (part: number, total: number) => total ? `${(part / total * 100).toFixed(1).replace(".", ",")}%` : "—";

function Ranking({ title, rows, metric = "sessions" }: { title: string; rows: Ga4SeriesRow[]; metric?: "sessions" | "screenPageViews" }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-900">{title}</h2><div className="mt-4 h-64">{rows.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={rows.slice(0, 10)} layout="vertical" margin={{ left: 16 }}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="label" type="category" width={110} tick={{ fontSize: 11 }}/><Tooltip/><Bar dataKey={metric} name={metric === "sessions" ? "Sessões" : "Visualizações"} fill="#2563EB" radius={[0, 6, 6, 0]}/></BarChart></ResponsiveContainer> : <Empty/>}</div></article>;
}

function Empty() { return <div className="flex h-full items-center justify-center rounded-xl bg-slate-50 text-sm text-slate-500">Ainda não há dados neste período.</div>; }

function Metric({ label, value, note }: { label: string; value: string; note?: string }) {
  return <article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-[#0B2D6B]">{value}</p>{note ? <p className="mt-2 text-xs text-slate-500">{note}</p> : null}</article>;
}

export function AcquisitionReport({ report, summary, gaUnavailable, firstPartyUnavailable }: { report: Ga4AcquisitionReport | null; summary: Summary | null; gaUnavailable: boolean; firstPartyUnavailable: boolean }) {
  const sessions = report?.totals.sessions;
  const stages = [
    { label: "Chegadas ao site", value: summary?.arrivals, note: "Requisições HTML com UTMs válidas; não são usuários únicos." },
    { label: "Sessões GA4", value: sessions, note: "Sujeitas ao consentimento, bloqueadores e regras do GA4." },
    { label: "Cadastro iniciado", value: summary?.signupStarts, note: "Primeira interação com o formulário de criação de conta." },
    { label: "Cadastro concluído", value: summary?.signups, note: "Conta nova criada com sessão iniciada." },
    { label: "Visitou Premium", value: summary?.premium, note: "Evento interno de visualização de /premium." },
    { label: "Checkout iniciado", value: summary?.checkouts, note: "URL válida retornada pela preparação do checkout." },
  ];
  const rawSources = report?.sources.map((row) => { const [source, medium] = row.label.split(" / "); return { ...row, label: channelName(source, medium), raw: row.label }; }) ?? [];
  const publicPages = report?.landingPages.filter((row) => isPublicLanding(row.label.split("?")[0])) ?? [];
  const otherPages = report?.pagePaths ?? [];
  const deviceTotal = report?.devices.reduce((sum, row) => sum + row.sessions, 0) ?? 0;

  return <div className="space-y-5">
    {gaUnavailable ? <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Google Analytics indisponível; métricas internas permanecem disponíveis.</p> : null}
    {firstPartyUnavailable ? <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Métricas internas indisponíveis; o relatório GA4 permanece disponível.</p> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Indicadores de aquisição">
      <Metric label="Usuários GA4" value={report ? format(report.totals.activeUsers) : "—"}/><Metric label="Sessões GA4" value={sessions === undefined ? "—" : format(sessions)}/><Metric label="Novos usuários GA4" value={report ? format(report.totals.newUsers) : "—"}/><Metric label="Visualizações GA4" value={report ? format(report.totals.screenPageViews) : "—"}/>
      <Metric label="Chegadas de campanhas" value={summary ? format(summary.arrivals) : "—"}/><Metric label="Cadastros iniciados" value={summary ? format(summary.signupStarts) : "—"}/><Metric label="Cadastros concluídos" value={summary ? format(summary.signups) : "—"}/><Metric label="Cadastros TikTok" value={summary ? format(summary.tiktokSignups) : "—"}/><Metric label="Visitas Premium" value={summary ? format(summary.premium) : "—"}/><Metric label="Checkouts iniciados" value={summary ? format(summary.checkouts) : "—"}/><Metric label="Chegada → início" value={summary ? ratio(summary.signupStarts, summary.arrivals) : "—"}/><Metric label="Início → cadastro" value={summary ? ratio(summary.signups, summary.signupStarts) : "—"}/><Metric label="Cadastro → checkout" value={summary ? ratio(summary.checkouts, summary.signups) : "—"}/>
    </section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-900">Funil de aquisição</h2><p className="mt-1 text-sm text-slate-600">Etapas independentes, não uma coorte de usuários. As taxas são razões entre contagens e podem refletir pessoas ou sessões diferentes.</p><ol className="mt-4 grid gap-3 md:grid-cols-3 xl:grid-cols-6">{stages.map((stage, index) => <li key={stage.label} className="rounded-xl bg-slate-50 p-4" title={stage.note}><p className="text-xs font-bold text-slate-500">{index + 1}. {stage.label}</p><p className="mt-1 text-2xl font-black text-[#0B2D6B]">{stage.value === undefined ? "—" : format(stage.value)}</p><p className="mt-1 text-xs text-slate-600">{index && stage.value !== undefined && stages[index - 1].value !== undefined ? `${ratio(stage.value, stages[index - 1].value!)} da etapa anterior` : stage.note}</p></li>)}</ol></section>
    <details className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-black">Como ler estes dados</summary><p className="mt-3 text-sm text-slate-600">Cliques no anúncio são medidos no TikTok Ads e não estão neste painel. Chegadas são requisições detectadas pelo servidor com UTMs válidas, sem identificação do visitante. Sessões são medidas pelo GA4 e podem ser menores por consentimento, bloqueadores e regras próprias. Cadastro concluído representa uma conta nova criada com sessão imediata. Visita Premium não é checkout; checkout só é contado após a preparação bem-sucedida da URL Hotmart. Campanhas e criativos dependem de UTMs e de atribuição consentida após a chegada.</p></details>
    {report ? <><article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Tráfego por dia</h2><div className="mt-4 h-72">{report.daily.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={report.daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label" tick={{ fontSize: 11 }}/><YAxis allowDecimals={false}/><Tooltip/><Line type="monotone" dataKey="sessions" name="Sessões" stroke="#2563EB" strokeWidth={3}/><Line type="monotone" dataKey="activeUsers" name="Usuários" stroke="#F59E0B" strokeWidth={2}/></LineChart></ResponsiveContainer> : <Empty/>}</div></article><section className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Origem / medium</h2><ul className="mt-3 space-y-2 text-sm">{rawSources.slice(0, 12).map((row) => <li key={row.raw} className="flex justify-between gap-3" title={`Valor original: ${row.raw}`}><span>{row.label}<small className="ml-2 text-slate-500">({row.raw})</small></span><strong>{format(row.sessions)}</strong></li>)}</ul></article><article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Dispositivos</h2><ul className="mt-3 space-y-2 text-sm">{report.devices.map((row) => <li key={row.label} className="flex justify-between"><span>{row.label === "mobile" ? "Mobile" : row.label === "desktop" ? "Desktop" : row.label === "tablet" ? "Tablet" : row.label}</span><strong>{format(row.sessions)} · {ratio(row.sessions, deviceTotal)}</strong></li>)}</ul></article><Ranking title="Landing pages públicas" rows={publicPages}/><Ranking title="Páginas mais acessadas" rows={otherPages} metric="screenPageViews"/></section></> : null}
    {summary ? <><section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Desempenho por campanha</h2><table className="mt-4 w-full min-w-[1040px] text-left text-sm"><thead><tr className="border-b text-slate-500">{["Campanha", "Source", "Medium", "Chegadas", "Sessões GA4", "Inícios", "Cadastros", "Premium", "Checkouts", "Conv. início", "Conv. cadastro"].map((label) => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{summary.campaigns.map((row) => <tr key={row.key} className="border-b"><td className="p-2">{row.campaign}</td><td className="p-2" title={`Raw: ${row.source} / ${row.medium}`}>{row.channel}<small className="block text-slate-500">{row.source}</small></td><td className="p-2">{row.medium}</td><td className="p-2">{format(row.arrivals)}</td><td className="p-2">{format(row.sessions)}</td><td className="p-2">{format(row.signupStarts)}</td><td className="p-2">{format(row.signups)}</td><td className="p-2">{format(row.premium)}</td><td className="p-2">{format(row.checkouts)}</td><td className="p-2">{ratio(row.signupStarts, row.arrivals)}</td><td className="p-2">{ratio(row.signups, row.signupStarts)}</td></tr>)}</tbody></table>{!summary.campaigns.length ? <p className="py-4 text-sm text-slate-500">Nenhuma campanha com dados no período.</p> : null}</section><section className="overflow-x-auto rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">Desempenho por criativo</h2><table className="mt-4 w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-slate-500">{["Criativo (utm_content)", "Chegadas", "Sessões", "Inícios", "Cadastros", "Checkouts", "Conv. início"].map((label) => <th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{summary.creatives.map((row) => <tr key={row.content} className="border-b"><td className="p-2">{row.content}</td><td className="p-2">{format(row.arrivals)}</td><td className="p-2">{format(row.sessions)}</td><td className="p-2">{format(row.signupStarts)}</td><td className="p-2">{format(row.signups)}</td><td className="p-2">{format(row.checkouts)}</td><td className="p-2">{ratio(row.signupStarts, row.arrivals)}</td></tr>)}</tbody></table>{!summary.creatives.length ? <p className="py-4 text-sm text-slate-500">Nenhum criativo identificado no período.</p> : null}</section></> : null}
  </div>;
}
