"use client";

import type { ReactElement } from "react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { HotmartFinanceReport } from "@/lib/billing/hotmart-api";

const formatMoney = (value: number, currency = "BRL") => new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(value);
export function FinanceReport({ report }: { report: HotmartFinanceReport }) {
  const tiers = [{ name: "Founder", value: report.founderActive }, { name: "Standard", value: report.standardActive }];
  const statuses = [{ name: "Ativas", value: report.activeSubscriptions }, { name: "Canceladas", value: report.canceledSubscriptions }, { name: "Reembolsos", value: report.refunds }, { name: "Chargebacks", value: report.chargebacks }];
  return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="Transações" value={String(report.transactions.length)}/><Card label="Receita bruta" value={report.gross ? formatMoney(report.gross.value, report.gross.currency) : "Múltiplas moedas"}/><Card label="Comissão do produtor" value={report.producerCommission ? formatMoney(report.producerCommission.value, report.producerCommission.currency) : "Múltiplas moedas"}/><Card label="MRR documentado" value={report.mrr ? formatMoney(report.mrr.value, report.mrr.currency) : "Múltiplas moedas"}/></section><section className="grid gap-5 lg:grid-cols-2"><Chart title="Receita por dia"><LineChart data={report.daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis/><Tooltip formatter={(value) => formatMoney(Number(value))}/><Line dataKey="gross" name="Receita bruta" stroke="#2563EB" strokeWidth={3}/></LineChart></Chart><Chart title="Transações por dia"><BarChart data={report.daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="transactions" name="Transações" fill="#F59E0B" radius={[6,6,0,0]}/></BarChart></Chart><Chart title="Founder x Standard"><BarChart data={tiers}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" name="Assinaturas ativas" fill="#2563EB" radius={[6,6,0,0]}/></BarChart></Chart><Chart title="Status e ocorrências"><BarChart data={statuses}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="value" name="Quantidade" fill="#0B2D6B" radius={[6,6,0,0]}/></BarChart></Chart></section><p className="rounded-xl bg-blue-50 p-4 text-xs text-blue-900"><strong>Fórmula do MRR:</strong> {report.mrrFormula}<br/><strong>Catálogo:</strong> Founder {report.founderOfferFound ? "confirmada" : "não encontrada"}; Standard {report.standardOfferFound ? "confirmada" : "não encontrada"}; {report.subscriptionPlansFound} plano(s) retornado(s).</p></div>;
}
function Card({ label, value }: { label: string; value: string }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-[#0B2D6B]">{value}</p></article>; }
function Chart({ title, children }: { title: string; children: ReactElement }) { return <article className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black text-slate-900">{title}</h2><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></article>; }
