import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { isBlocked, nextFailureState, type LoginFailureState } from "../src/lib/security/login-policy";

const rate = readFileSync("src/lib/security/auth-rate-limit.ts", "utf8");
const login = readFileSync("src/app/api/auth/login/route.ts", "utf8");
const migration = readFileSync("supabase/migrations/20260915084514_security_hardening_admin_control_center.sql", "utf8");
assert.match(rate, /AUTH_LOGIN_MAX_ATTEMPTS", 5/);
assert.match(rate, /createHmac\("sha256"/);
assert.doesNotMatch(rate, /localStorage/);
assert.match(login, /status: 429/);
assert.match(login, /E-mail ou senha inválidos/);
assert.doesNotMatch(login, /error\.message/);
assert.match(login, /clearLoginFailures/);
assert.match(migration, /revoke all on table public\.auth_login_limits from public, anon, authenticated/);
assert.equal(migration.includes("grant execute on function public.record_login_failure(text,text,integer,integer,integer) to service_role"), true);
const policy = { maxAttempts: 5, windowMs: 15 * 60_000, cooldownMs: 15 * 60_000 };
let state: LoginFailureState | null = null;
for (let attempt = 0; attempt < 4; attempt++) state = nextFailureState(state, attempt * 1000, policy);
assert.equal(isBlocked(state, 4000), false, "four failures remain allowed");
state = nextFailureState(state, 4000, policy);
assert.equal(isBlocked(state, 4001), true, "fifth failure arms the cooldown for the next request");
assert.match(login, /return Response\.json\(\{ error: INVALID \}, \{ status: 401 \}\)/, "the fifth failed response remains generic");
assert.match(login, /if \(current\.blocked\)/, "the sixth request is rejected before authentication");
assert.equal(isBlocked(state, 15 * 60_000 + 4001), false, "cooldown expires");
const accountA = new Map<string, LoginFailureState | null>([["account-a:origin-a", state]]);
assert.equal(accountA.has("account-b:origin-a"), false, "another account is isolated");
assert.equal(accountA.has("account-a:origin-b"), false, "another origin is isolated");
state = null;
assert.equal(isBlocked(state, 0), false, "successful login cleanup clears failures");
console.log("Security: rate limit, generic messages, cleanup and least privilege validated.");
